### PR TITLE
v2 progress

### PR DESCRIPTION
**Pull request by colby-swandale**
This pull request will serve as a progress indicator on work i am doing to bring this gem up to date and move from the now deprecated Vimeo v2 API to v3 (Current)

- [x] Clean up and update gem from some use of old conventions
- [ ] Implement Vimeo v3 API (This is quite an epic story, so i will break this down in the next few days)
- [ ] Update tests to reflect all changes

All feedback is welcome.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Sorry for the delay, here are the stories for the implementation of the Vimeo V3 API
- [ ] Decide on design pattern that fits into Vimeos API model
I am getting some ideas from [sferik/twitter](https://github.com/sferik/twitter), but seeing how Vimeo has nested resources in some areas i will need to adjust the design to fit into this. Open to ideas if anyone has any.

- [ ] Implement Categories endpoint and functions
- [ ] Implement Channels endpoint and functions
- [ ] Implement Groups endpoint and functions
- [ ] Implement On Demand endpoint and functions
- [ ] Implement Tags endpoint and functions
- [ ] Implement Users endpoint and functions
- [ ] Implement Videos endpoint and functions

**Comment by colby-swandale** [comment]
I have worked with a few design choices and i think i have come up with a solution that i think will work quite well. 

```
# Create a new Vimeo client with the required access_token to interface with 
# Vimeo's API
client = Vimeo::Client.new do |client|
  client.access_token = 'ah'
end

# Vimeo has 7 top resources: Categories, Channels, Groups, Me, On Demand, Tags
# Users, Videos. I am going to make the pluralized form of the resource publically
# avaliable in the client. Each resource will also be class to allow
# access to attrs and to sub functions ie: /categories/#{id}/users.
# A usage example would be as such.

categories  = client.categories # => [Vimeo::Entities::Category]
channels    = client.channels   # => [Vimeo::Entities::Channel]

users = channel.first.users     # => [Vimeo::Entities::User]
users.first.name                # => "My Vimeo Name"
```

**Comment by chrispatterson** [comment]
@colby-swandale You are credit to team. I was just looking at rolling my own v3 Vimeo solution - though it'd probably be sufficient for my (narrow) purposes, I'd love to have a more fully-featured option like you're building. :clap:

**Comment by colby-swandale** [comment]
Hey Guys,

Quick update, i have started the request and response implementation. At the moment i can make a good request and build a category object from its response. Though that was through manual debugging and still yet to write tests to confirm the functionality is working. So a good part almost out of the way but still a long road ahead.

Sorry this progress has been quite slow, i am juggling between life/work but i promise i will keep working on this. 
Thanks Guys!

@chrispatterson thanks! appreciated a lot.

**Comment by colby-swandale** [comment]
Hi everyone,

Anyone keeping an eye on this PR would have noticed that i have not made any commits for quite some time. Don't worry i have not abandoned this project, my only computer died a few weeks back and had to wait for a replacement to arrive. Numerous personal events has also eaten most of the my spare time that i can allocate to this project but i now will start putting some time down again to work on this.

Thanks guys!

**Comment by chrispatterson** [comment]
@colby-swandale Vimeo integration has moved onto my plan for the next week or so. I'd love to use your work - any chance this will be in shape for use by then, or should I plan on rolling my own for now at least?

I appreciate the work you've been doing, and will probably want to revisit using this regardless whether it's a fit for my immediate needs. Just trying to plan my time allocation. :thumbsup:

**Comment by colby-swandale** [comment]
@chrispatterson i wouldn't bet on it, the code is fairly unstable right now and i could bring in a breaking change at any point until i release a beta so i would advise you either see if you can use the current version of the this gem or roll a quick implementation yourself. If you need any help let me know.

**Comment by chrispatterson** [comment]
@colby-swandale After a couple of months of having other issues frontburnered ahead of this, I'm *finally* looking at vimeo integration.

I'm guessing this is still not ready for production use, so I've taken a pass at a simple vimeo upload, but have kind of run aground. I'm getting an error about bytesize not being defined for a hash, which makes me suspect Faraday isn't using multipart, but when I inspect the connection it appears to be using the `Faraday::Request::Multipart` builder.

All videos will be uploaded using a single account, and I don't need any management support apart from being able to upload videos and store the resulting vimeo id. My basic module and more details are at https://gist.github.com/chrispatterson/6545e7413d430afa34ed, and any input is much appreciated. (It feels like I'm missing something obvious).

Thanks in advance for the help.

**Comment by colby-swandale** [comment]
This is going to be my last update as i have run out of steam to put more work into this pull request. We're not using Vimeo any longer at my place of employment and finding time to work on this is becoming increasingly difficult. I am going to close this PR but anyone is welcome to continue working and making improvements if you desire.

**Pull request closed without merging**
